%ifndef DEFINES_INC
    %define DEFINES_INC

    %define SYSCALL_EXIT    60
    %define SYSCALL_READ    0
    %define SYSCALL_WRITE   1
    %define FD_STDIN        0
    %define FD_STDOUT       1
    %define FD_STDERR       2
    %define SYMBOL_SPACE    ' '
    %define SYMBOL_LF       `\n`
    %define SYMBOL_TAB      `\t`
    %define SYMBOL_MINUS    '-'
    %define ERROR_CODE      1
    %define SUCCESS_CODE    0

%endif
